 CREATE USER WMS_AUDIT
  IDENTIFIED BY WMS_AUDIT
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Tablespace Quota for WMS_AUDIT
  ALTER USER WMS_AUDIT QUOTA UNLIMITED ON USERS;


 GRANT CONNECT TO WMS_AUDIT;
  GRANT RESOURCE TO WMS_AUDIT;
 GRANT CREATE SESSION TO WMS_AUDIT;

 CREATE TABLE WMAAUDITENTRY
(
    ID NUMBER(10,0) PRIMARY KEY NOT NULL,
    PROCESSDEFINITIONID VARCHAR2(10),
    ACTIVITYDEFINITIONID VARCHAR2(10),
    INITIALPROCESSINSTANCEID VARCHAR2(10),
    CURRENTPROCESSINSTANCEID VARCHAR2(10),
    ACTIVITYINSTANCEID VARCHAR2(10),
    WORKITEMID VARCHAR2(10),
    PROCESSSTATE VARCHAR2(10),
    EVENTCODE NUMBER(2,0),
    DOMAINID VARCHAR2(10),
    NODEID VARCHAR2(10),
    USERID VARCHAR2(10),
    ROLEID VARCHAR2(10),
    TIME TIMESTAMP,
    INFORMATIONID VARCHAR2(10)
);

CREATE SEQUENCE WMAAuditEntry_Sequence
START WITH     1
INCREMENT BY   1
NOCACHE
NOCYCLE;