 CREATE USER WMS_AUDIT
  IDENTIFIED BY WMS_AUDIT
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Tablespace Quota for WMS_AUDIT
  ALTER USER WMS_AUDIT QUOTA UNLIMITED ON USERS;


 GRANT CONNECT TO WMS_AUDIT;
  GRANT RESOURCE TO WMS_AUDIT;
 GRANT CREATE SESSION TO WMS_AUDIT;