 CREATE USER WMS_AUDIT
  IDENTIFIED BY WMS_AUDIT
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Tablespace Quota for WMS_AUDIT
  ALTER USER WMS_AUDIT QUOTA UNLIMITED ON USERS;


 GRANT CONNECT TO WMS_AUDIT;
  GRANT RESOURCE TO WMS_AUDIT;
 GRANT CREATE SESSION TO WMS_AUDIT;


CREATE SEQUENCE WMAAuditEntry_Sequence
START WITH     1
INCREMENT BY   1
NOCACHE
NOCYCLE;

CREATE TABLE "WMS_AUDIT"."WM_AUDIT_ENTRY"
   (	"ID" NUMBER(10,0),
	"PROCESS_DEFINITION_ID" VARCHAR2(10),
	"ACTIVITY_DEFINITION_ID" VARCHAR2(10),
	"INITIAL_PROCESS_INSTANCE_ID" VARCHAR2(36),
	"CURRENT_PROCESS_INSTANCE_ID" VARCHAR2(10),
	"ACTIVITY_INSTANCE_ID" VARCHAR2(10),
	"WORK_ITEM_ID" VARCHAR2(10),
	"PROCESS_STATE" VARCHAR2(36),
	"EVENT_CODE" NUMBER(2,0),
	"DOMAIN_ID" VARCHAR2(10),
	"NODE_ID" VARCHAR2(10),
	"USER_ID" VARCHAR2(10),
	"ROLE_ID" VARCHAR2(10),
	"TIME" TIMESTAMP (6),
	"INFORMATION_ID" VARCHAR2(10),
	"PROCESS_DEF_BUSINESS_NAME" VARCHAR2(40),
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"

CREATE TABLE "WMS_AUDIT"."WM_EVENT_CODE"
   (	"ID" NUMBER(2,0),
	"CODE" VARCHAR2(50) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(150),
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"


  ALTER TABLE  WM_AUDIT_ENTRY  ADD CONSTRAINT FK_Event_Code FOREIGN KEY (EVENT_CODE) REFERENCES WM_EVENT_CODE(ID);
