wfmc:
    service:
        instanceName: wapi-elo-renns
        instanceClass: org.wfmc.elo.WfmcServiceEloImpl
    cacheService:
        instanceName: wapi-cache-in-memory
        instanceClass: org.wfmc.service.WfmcServiceCacheMemoryImpl
        timeToExpire: 100000
        timeToLive: 200000
        timeToEvict: 300000
    wmConnectInfo:
        userIdentification: Administrator
        password: elo@RENNS2015
        engineName: Wfmc Test
        scope: http://10.6.38.90:8080/ix-elo/ix