spring:
    wfmcAuditDatasource:
        dataSourceClassName: oracle.jdbc.pool.OracleDataSource
        url: jdbc:oracle:thin:@//10.6.38.61:1521/renns
        databaseName: renns
        serverName: 10.6.38.61
        username: WMS_AUDIT
        password: WMS_AUDIT
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true


    jpa:
        database-platform: org.hibernate.dialect.Oracle9iDialect
        database: Oracle
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.hbm2ddl.auto: validate